### PR TITLE
Remove early return from HoverMenuView.onLayout to prevent menu enter…

### PR DESCRIPTION
**Pull request by Fitzpasd**
…ing unresponsive state when content has changed during COLLAPSED state

Fix for issue #34

### CODE REVIEW

**Comment by Fitzpasd** [comment]
I signed it!

**Comment by matthew-carroll** [comment]
Hi.  Can you describe what you mean by "unresponsive state"?  What is the problem you're seeing?

**Comment by Fitzpasd** [comment]
After some more testing, this doesn't fix the issue #35.  Closing this PR and digging deeper into the problem.

**Comment by matthew-carroll** [comment]
Ok, can you describe the problem you're seeing?

**Comment by Fitzpasd** [comment]
Opened an issue that has more details.  #34 

I've uploaded a sample app that displays the issue [here](https://github.com/Fitzpasd/hoverbug)

Changing content and notifying the listeners causes the collapsed menu to move to the top of the screen and become unresponsive.

before

Initial state of menu.  Works as expected.

after

Press 'add content':  Menu moves to top right corner, and no longer responds to input.  'Add content' simply adds another NavigatorContent to the adapter and calls onChange to all the listeners.

**Pull request closed without merging**
